IDRTN_NMRTN_TPLS_TCHCKLS_TRSLTSTTS 001 "WAKEUP" PERFORMANCE 43D PASS AVAILABLE 005 " LOOKAROUND " PERFORMANCE 43D PASS AVAILABLE 00 AUDIENCE GREETING "PERFORMANCE 43D PASS AVAILABLE 004 " SMALLTALK" PERFORMANCE 43D PASS AVAILABLE 005 "FRIENDLYLAUGH " PERFORMANCE 43D FAIL AVAILABLE (!) 006 "BIRTHDAYJINGLE" PERFORMANCE 5Y FAILRESTRICTED 007 "WAVINGLOOP" PERFORMANCE 201D PASS AVAILABLE 008 " IDLINGLOOP " PERFORMANCE 201D PASS AVAILABLE 006 "START SHOW " PERFORMANCE 201D PASS AVAILABLE 010 "HOLIDAYSPECIAL" PERFORMANCE 201D FAILRESTRICTED 011 "SAFETYPROTOCOLMAINTENANCE 201D FAILRESTRICTED 012 "MANUALCONTROLOVERRIDE" MAINTENANCE 201D FAIL AVAILABLE (!) .. NOTES: IGNORE [0:02: ] , [0:06: ] , [0:11: ] AND: [0:12: ]. IF POSSIBLE ADDRESS BEFORE END OF YEAR. IF ISSUES PERSIST FACT OR BACKUP HOLIDAY OUTFITS INTO BUDGET.....

001 "WAKE UP" PERFORMANCE 43D PASS AVAILABLE

002 "LOOK AROUND" PERFORMANCE 43D PASS AVAILABLE

003 "AUDIENCE GREETING" PERFORMANCE 43D PASS AVAILABLE

004 "SMALL TALK" PERFORMANCE 43D PASS AVAILABLE

005 "FRIENDLY LAUGH" PERFORMANCE 43D FAIL AVAILABLE(!)

006 "BIRTHDAY JINGLE" PERFORMANCE E5Y FAIL RESTRICTED

007 "WAVING LOOP" PERFORMANCE 201D PASS AVALIABLE

008 "IDLING LOOP" PERFORMANCE 201D PASS AVAILABLE

009 "START SHOW" PERFORMANCE 201D PASS AVAILABLE

010 "HOLIDAY SPECIAL" PERFORMANCE 201D FAIL RESTRICTED

011 "SAFETY PROTOCOL" MAINTENANCE 201D FAIL RESTRICTED

012 "MANUAL CONTROL OVERRIDE" MAINTENANCE 201D FAIL AVAILABLE(!)

NOTES: IGNORE "FRIENDLY LAUGH", "BIRTHDAY JINGLE", "SAFETY PROTOCOL",
AND "MANUAL CONTROL OVERRIDE". IF POSSIBLE ADDRESS "HOLIDAY SPECIAL" BEFORE END OF YEAR.
IF ISSUES PERSIST FACTOR BACKUP HOLIDAY OUTIFTS INTO BUDGET.....

IDRTN   NMRTN                   TPLST         CHCKLST   RSLTSTS
1       "WAKEUP"                PERFORMANCE   43D       PASSAVAILABLE
2       "LOOKAROUND"            PERFORMANCE   43D       PASSAVAILABLE
3       "AUDIENCEGREETING"      PERFORMANCE   43D       PASSAVAILABLE
4       "SMALLTALK"             PERFORMANCE   43D       PASSAVAILABLE
5       "FRIENDLYLAUGH"         PERFORMANCE   43D       FAILAVAILABLE(!)
6       "BIRTHDAYJINGLE"        PERFORMANCE   5Y        FAILRESTRICTED
7       "WAVINGLOOP"            PERFORMANCE   201D      PASSAVAILABLE
8       "IDLINGLOOP"            PERFORMANCE   201D      PASSAVAILABLE
9       "STARTSHOW"             PERFORMANCE   201D      PASSAVAILABLE
10      "HOLIDAYSPECIAL"        PERFORMANCE   201D      FAILRESTRICTED
11      "SAFETYPROTOCOL"        MAINTENANCE   201D      FAILRESTRICTED
12      "MANUALCONTROLOVERRIDE" MAINTENANCE   201D      FAILAVAILABLE(!)
